### ISSUE TITLE
Mouse Sensitivity Extremely Low

### ISSUE THREAD

**Issue by cbarter** [Rain9333/MagicMouse2DriversWin10x64#4]
So I installed the driver and updated the device to use the driver, scrolling is working now but the sensitivity dropped to about half? I maxed out my system settings so it's better, but it's still a little bit under what I like it at, and if I use another mouse the sensitivity is through the roof.

Is the driver straight from bootcamp or is this some custom work of yours @Rain9333 ?

Any thoughts on how I might improve this would be welcome, happy to contribute if needed.

**Comment by xpierrohk** [comment]
He used brigadier, according to the readme, which seems to be a driver downloader for apple stuff, so I wouldn't expect him to know how to config it. I'm looking to flip the scroll direction myself :D

**Comment by cbarter** [comment]
> He used brigadier, according to the readme, which seems to be a driver downloader for apple stuff, so I wouldn't expect him to know how to config it. I'm looking to flip the scroll direction myself :D

You can flip the scroll direction in the registry. If you google it you should find instructions. Just use regedit and find the device.

And yeah, I figured that out I after a bit..., Explains why the bootcamp drivers never worked when extracting them, they were so old, apple delivers bootcamp differently now. Was able to use brigadier to get my keyboard drivers too. Sucks that the drivers have such low sensitivity.

**Comment by xpierrohk** [comment]
Yup found it thx ! At the apple store they were looking as if I was a complete idiot to buy an apply keyboard and mouse for a PC, but I just find them small and nice, I dont get why they can't make them fully compatible.
